name: Auto Create GraphQL Issues

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/issues/graphql-integration.yml'

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            
            // Ler arquivo de issues
            const issuesFile = fs.readFileSync('.github/issues/graphql-integration.yml', 'utf8');
            const issues = yaml.load(issuesFile);
            
            console.log('Creating issues...');
            
            for (const issue of issues.issues) {
              const { data } = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issue.title,
                body: issue.body,
                labels: issue.labels || []
              });
              
              console.log(`Created issue: ${data.html_url}`);
            }

